# Generated by Django 4.2.11 on 2024-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preco')),
                ('descricao', models.CharField(max_length=250, verbose_name='descricao')),
                ('estoque', models.IntegerField(default=0, verbose_name='estoque')),
            ],
        ),
    ]
